# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  theforgederby.co.uk:
    site_hosts:
      - canonical: theforgederby.test
        redirects:
          - www.theforgederby.test
    local_path: ../theforgederby.co.uk # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: skywriter@gmail.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false

  fitnessreoublic.co.uk:
    site_hosts:
      - canonical: fitnessrepublic.test
        redirects:
          - www.fitnessrepublic.test
    local_path: ../fitnessrepublic.co.uk # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: skywriter@gmail.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
