# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  staging.theforgederby.co.uk:
    site_hosts:
      - canonical: staging.theforgederby.co.uk
        redirects:
          - www.staging.theforgederby.co.uk
    local_path: ../theforgederby.co.uk # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:MagneticMule/wordpress-trellis-sites.git # replace with your Git repo URL
    repo_subtree_path: theforgederby.co.uk # relative path to your Bedrock/WP directory in your repo
    branch: staging
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true

  staging.fitnessrepublic.co.uk:
    site_hosts:
      - canonical: staging.fitnessrepublic.co.uk
    local_path: ../fitnessrepublic.co.uk # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:MagneticMule/wordpress-trellis-sites.git # replace with your Git repo URL
    repo_subtree_path: fitnessrepublic.co.uk # relative path to your Bedrock/WP directory in your repo
    branch: staging
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true

  staging.hiddenburton.uk:
    site_hosts:
      - canonical: staging.hiddenburton.uk
    local_path: ../hiddenburton.uk # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:MagneticMule/wordpress-trellis-sites.git # replace with your Git repo URL
    repo_subtree_path: hiddenburton.uk # relative path to your Bedrock/WP directory in your repo
    branch: staging
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
